id: P553598A7
initial_creation_type: input
source_metadata:
  title: Praise Series
  language: de
  description: 'A selection of praises (Skt. stotra; Tib. bstod pa) to various Buddhist
    deities and prominent masters (arranged according to subject):'
  volume:
    d34799739c6240a1804887e1e4a98179:
      title: Verses of Homage to the Buddhas and Bodhisattvas Together with their
        Mantras
      parent: General
    27169390cedf45f796bc0bb05d8cd656:
      title: 'The Sun that Causes the Lotus of Intelligence to Bloom: In Praise of
        the Lineage of Gurus for the Noble Abhidharma'
      parent: Abhidharma Lineage
    6d9770ea7c0c4c9daf4d0d1fe709e249:
      title: Verses in Praise of the Protector Akṣobhya
      parent: Akṣobhya
    d12f9aa04e5a42e482d4dd6909d1ae4f:
      title: Praise of Noble Avalokiteśvara
      parent: Avalokiteśvara
    eb1781b793a8415ea91677f481deee07:
      title: Praise of Noble Avalokiteśvara (Tengyur version)
      parent: Avalokiteśvara
    4999fbdcb1844e08af3d5175f8d96389:
      title: Short Praise of the Buddha's Deeds
      parent: Buddha Śākyamuni
    f4ef762bdb1f474283a0e958572bb75a:
      title: Praise of the Twelve Acts of the Buddha
      parent: Buddha Śākyamuni
    a37910926f0a42429ce81ab2dabd9f87:
      title: In Praise of the Twelve Deeds of the Buddha
      parent: Buddha Śākyamuni
    1a17c974efa849d6aefeb9a1566fa698:
      title: 'Praise of the Buddha: With Skilful Means & Compassion...'
      parent: Buddha Śākyamuni
    334c6aa2a7ad4445a2b736b93962c38a:
      title: 'Introduction to the Buddha’s Words: A Praise and Aspiration Related
        to the Words of the Victorious One'
      parent: Buddha's Words
    945f5df855d046e8a13a68d7207602bb:
      title: 'A Beautiful Lotus Garland: In Praise of the Omniscient Lord of Dharma
        Butön Rinchen Drup'
      parent: Butön Rinchen Drup
    debbb67e7b46498cb31ecaf027754fe3:
      title: 'The Swift Infusion of Blessings: In Praise of the Mahāpaṇḍita Candragomin'
      parent: Candragomin
    9c2883c64e014282b5fc3058dca01d02:
      title: 'The Melodious Song of Joy: In Praise of the Master Candrakīrti'
      parent: Candrakīrti
    bd022f04223045eebe4412cd5669df3b:
      title: Praise of Candrakīrti
      parent: Candrakīrti
    c067a5ba63dd48229c4e07abb23389d0:
      title: 'The Excellent Bilva Tree of Auspiciousness: Praise and Prayer to Terchen
        Chokgyur Lingpa'
      parent: Chokgyur Dechen Lingpa
    ac85e5a00d424a6ca06911e24b5a71b5:
      title: A Homage to His Holiness the Dalai Lama
      parent: Fourteenth Dalai Lama
    985535ea17b84f9faaff45ce310ad328:
      title: Verses of Homage
      parent: Fourteenth Dalai Lama
    3cc4f63ecb6944059063f851ee56b95e:
      title: Praise of Kunga Yeshe, Great Being and Master of Extensive Scriptural
        Traditions
      parent: Ga Rabjampa Kunga Yeshe
    1ed862ca6eab4382b40e89e0001fe62d:
      title: 'Cloud Banks of Blessings: Praise and Prayer to the Vajradhara Ngawang
        Lekpa'
      parent: Gatön Ngawang Lekpa
    9ffdee278e9b4505a1d7afc8124c52b6:
      title: 'Thunderous Melody: In Praise of the Omniscient Gorampa Sonam Senge'
      parent: Gorampa Sonam Senge
    f53ce79048ea48768fcd1b24e5b82910:
      title: In Praise of Padmākara, the Great Guru of Uḍḍiyāna
      parent: Guru Padmasambhava
    13047a8b4daa42f0963ce9340792244a:
      title: 'The Three Kāyas: Praises to the Great Master Padmasambhava'
      parent: Guru Padmasambhava
    8b8d0473a2074b54bfb1d4b134e7e2fa:
      title: A Praise to the Lotus King
      parent: Guru Padmasambhava
    3840cb51a90a4233a20600718691cbae:
      title: 'Fully Blossomed Learning and Contemplation: A Praise of the Great Spiritual
        Friend Jamyang Gyaltsen'
      parent: Jamyang Gyaltsen
    c5baca7abc1b4168b592037ed85b6626:
      title: In Praise of Jamyang Khyentse Wangpo
      parent: Jamyang Khyentse Wangpo
    616ed804ebde422997a499a64b457124:
      title: 'The Bestowal of Supreme Blessings: Praise to the Vajradhara Loter Wangpo'
      parent: Jamyang Loter Wangpo
    a9efa75ac69e4a789039d9f34b8e3068:
      title: In Praise of Jigme Lingpa’s Pre-Eminence
      parent: Jigme Lingpa
    8caab1210a0b48a9b6fa51e73dacffc3:
      title: 'Sweet Melody to Delight the Glorious Deity: In Praise of Śrī Kālīdevī'
      parent: Kālīdevī
    3c4f50d06e96416fbf1add2d7fc59967:
      title: 'Beautiful Adornment of the Earth: In Praise of Kṣitigarbha'
      parent: Kṣitigarbha
    34be8febfa024e27ad4222243a88b909:
      title: In Praise of Longchenpa – The Greatness of the Omniscient Longchen Rabjam
      parent: Longchen Rabjam
    2127c727366648d0bc5688f3b4e2a2f8:
      title: In Praise of the Lords of the Three Families
      parent: Lords of the Three Families
    7d8ce92b9f9b4a139193183508604c06:
      title: 'Cutting through the Four Demons in Absolute Space: A Praise of Machik
        Labdrön'
      parent: Machik Labdrön
    356af636eda6457bac0d6772b8b812db:
      title: 'Music to Delight the Ḍākinī: A Praise to the Deathless Mandāravā'
      parent: Mandāravā
    7b68ba37faac4512a3491eeeedc4b6cb:
      title: 'The Fresh Saffron Flower: In Praise of Venerable Mañjughoṣa'
      parent: Mañjuśrī
    0a6a948465c04ec5b2edaf2c5db2ab9e:
      title: 'The Light of Wisdom: Praise to Mañjuśrī'
      parent: Mañjuśrī
    de238774d143444597b19afe62fe7ce6:
      title: 'The Lute of Vajra Harmony: Praise to the Protector Mañjuśrī'
      parent: Mañjuśrī
    6b4c1804304b4c28b1c2b02a6e178d47:
      title: 'The Swift Infusion of Blessings: In Praise of Mañjughoṣa'
      parent: Mañjuśrī
    c0f2f5055f3e468c8536b6f5b3441354:
      title: 'In Praise of Mañjuśrī: Increasing Intelligence to the Full'
      parent: Mañjuśrī
    7be919524b1646c1957681fd62fb7658:
      title: 'In Praise of Mañjuśrī: The Great Treasure of Blessings'
      parent: Mañjuśrī
    4ee15bd262264064bd3c2b557d254003:
      title: In Praise of the Protector Mañjughoṣa
      parent: Mañjuśrī
    b3f12bc490f344b681e03481d0b7cca8:
      title: Ultimate Praise of the Noble and Venerable Mañjuśrī
      parent: Mañjuśrī
    0d62397c9b77436e95c36b44cdaeaa48:
      title: Praise to Mañjughoṣa
      parent: Mañjuśrī
    95028e00a7704f74b1eccaf7431ad6a5:
      title: The Praise to Mañjuśrī—Glorious Wisdom's Excellent Qualities
      parent: Mañjuśrī
    a97249512f014ce6a77e5e97c36a7f4b:
      title: In Praise of the Goddess Mārīcī (Özerchenma)
      parent: Mārīcī
    09b7999f9f544435aabf98359e6b0a6c:
      title: In Praise of Jetsün Mila Shepa Dorje
      parent: Milarepa
    7e948a805c6d4417b10c10b7ea4a6806:
      title: 'The Definitive Ascertainment of Tantra: In Praise of the Great Master
        Milarepa'
      parent: Milarepa
    a7f1e2d555d548f4aed2b4400705ef98:
      title: Homage to Milarepa
      parent: Milarepa
    f2b2766956934bd28af6563bd397bcf7:
      title: 'The Purifier of Ethical Discipline: An Aspirational Praise to Vajradhara
        Kunga Zangpo'
      parent: Ngorchen Kunga Zangpo
    a58faf342944463fa357cf91e63633c4:
      title: In Praise of Patrul Orgyen Jigme Chökyi Wangpo
      parent: Patrul Rinpoche
    a97edcdcece44e6bb8be953a13e58e8a:
      title: In Praise of Sönam Palge
      parent: Rogza Sönam Palge
    21e0de154ea849f0a8e1b1ea6f6cf81c:
      title: A Short Guide to Yangleshö in Nepal
      parent: Sacred Places
    70b11752d9dd4147b6ad1968cbdeae48:
      title: 'A Song of Perfect Joy: In Praise of the Sacred Sites of Rājgṛha, Vulture
        Peak and Nālandā'
      parent: Sacred Places
    39da56589c574438a1ec0f3e13224d4a:
      title: In Praise of Devāvatāra, Site of Buddha's Descent from Heaven
      parent: Sacred Places
    9caecd713aac47a5b61bd08209a03c84:
      title: In Praise of Kuśinagara
      parent: Sacred Places
    ca93a8794a744e498fb2e8b88e81e7c7:
      title: In Praise of Vārāṇasī, the Supreme Place
      parent: Sacred Places
    da24558f292942fda3c3acd023b07f9e:
      title: In Praise of Yangleshö in Nepal
      parent: Sacred Places
    7bdfdf8faf044efc919de1670eb42cda:
      title: In Praise of the Great Indian City of Kolkata
      parent: Sacred Places
    7a48bd5d2ed545f9b7ef51029a6296a6:
      title: Offering Clouds to Delight the Victorious Ones, Combining A Praise of
        Redreng with a Prayer of Aspiration
      parent: Sacred Places
    91f6be8fbf574687b54c00007a51bf6c:
      title: Praise and Prayer to Kharchu, Great Sacred Place of Lhodrak
      parent: Sacred Places
    d73eac5e12224d70acb7979f0e89e0a8:
      title: 'The Conquerors'' Delight: In Praise of Śrāvastī'
      parent: Sacred Places
    bd8f3efaedf846bb81ad941a54af0127:
      title: 'The White Lotus Garland of Immortality: In Praise of the Supreme Vajra
        Place, Tso Pema (Lotus Lake)'
      parent: Sacred Places
    a16a3fa49bbf494c95fd04c41207b57b:
      title: 'The White Lotus: In Praise of Lumbinī'
      parent: Sacred Places
    95bd9fc45a3b4d21a72dbdada9235b06:
      title: 'Melodious Sound: In Praise of Vulture Peak Mountain'
      parent: Sacred Places
    fec10eeca626452d88364013b807c88a:
      title: Praise to Sakya Paṇḍita
      parent: Sakya Paṇḍita
    1a36b26ba0f6486e894d129de1b3ea64:
      title: 'Gentle Splendour: Praises to the Great Abbot Śāntarakṣita'
      parent: Śāntarakṣita
    677514d782fd49959e3719c6291f3610:
      title: 'Ripples on the Ganges: In Praise of the Goddess Sarasvatī'
      parent: Sarasvatī
    21846de7e10f4e48b014bdfb0a824105:
      title: 'The Melodious Song of Vajra Harmony: In Praise of Red Sarasvatī'
      parent: Sarasvatī
    199c5beb49e74dbdaad1d40a9fe2632c:
      title: 'The Sweet Sound of Perfect Joy: In Praise of the Goddess Sarasvatī'
      parent: Sarasvatī
    bf37a36fda3f4cf9bfa7381d2aa8f4eb:
      title: 'Intensely Brilliant Wisdom: In Praise of the Great Elder Smṛtijñāna'
      parent: Smṛtijñānakīrti
    9037825de66946119e4e4ce6c41f7fb8:
      title: The Praise to Tārā with Twenty-One Verses of Homage and The Excellent
        Benefits of Reciting the Praise
      parent: Tārā
    202efe95ffe24b20ab42e9e383c5f117:
      title: 'The Fulfilment of All Aspirations: In Praise of Noble Tārā'
      parent: Tārā
    d8adb567e10a4f428cf2db58b13086da:
      title: 'Flower of Faith: In Praise of Tāranātha, Lord of Secrets'
      parent: Tāranātha
    5f56f0ba0f914c7d8ae283d0c13fd058:
      title: 'A Blossoming of the Intellect: In Praise of the Great Pioneer Thönmi
        Sambhoṭa'
      parent: Thönmi Sambhoṭa
    75657902fcc5426b9a63f7d7de3eafd2:
      title: In Praise of the Three Jewels
      parent: Three Jewels
    71378bfd44f64bebb33c4cb597b64378:
      title: 'Snowy Lands: Praises to the Great Dharma Emperor Tri Songdetsen'
      parent: Tri Songdetsen
    3bd529ea2f864f4abf4b1b4928d69684:
      title: 'The Flower of Faith: Praise to the Great Lord Guru Tsongkhapa'
      parent: Tsongkhapa Lobzang Drakpa
    73901ea1770247958aef510054e2f8af:
      title: A Song of Innermost Praise to Vajrasattva
      parent: Vajrasattva
    3173eb708bcc4cb9931796c29059e96f:
      title: 'Wish-Granting Provision of Twofold Accomplishment: A Praise of Vajrasattva'
      parent: Vajrasattva
    28e254dd772d4b13a1a0734991cd803d:
      title: In Praise of Glorious Vajrasattva
      parent: Vajrasattva
    910cff82aad14c6094ee30f10757f963:
      title: 'The Staircase Ascending to Khecara: A Praise in Accord with the Arrangement
        of the Realm of Holy Nāro Khecarī'
      parent: Vajrayoginī
    fde0e03dec51490688466013c6ad6dfa:
      title: 'The Hero''s Bellowing Laughter: In Praise of the Lord of Yogins'
      parent: Virūpa
created_at: '2022-03-01T05:11:17.792255'
last_modified_at: '2022-03-01T05:11:17.792258'
